In [2]:
import numpy as np

In [3]:
## Numpy Arrays

In [5]:
my_list=[1,2,3]

In [6]:
arr=np.array(my_list)

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
mat=np.array(my_mat)

In [9]:
mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(4)

array([0.17942831, 0.9106867 , 0.50370322, 0.08988954])

In [17]:
np.random.rand(5,5)

array([[0.46985567, 0.509011  , 0.21419934, 0.82539527, 0.0080965 ],
       [0.37053956, 0.54409845, 0.99864998, 0.49526033, 0.36180329],
       [0.57458326, 0.14002895, 0.65860476, 0.82851665, 0.19461433],
       [0.9072823 , 0.82843602, 0.90168224, 0.15644132, 0.3237471 ],
       [0.97877278, 0.55166802, 0.13124314, 0.15273945, 0.76770623]])

In [18]:
np.random.randn(2)

array([ 1.10655917, -0.50469025])

In [20]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
randr=np.random.randint(0,50,10)
randr

array([45, 37, 26,  2, 48, 22, 36, 12, 34, 44])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
randr.max()

48

In [28]:
randr.min()

2

In [29]:
randr.argmax()

4

In [30]:
randr.argmin()

3

In [32]:
randr.shape

(10,)

In [33]:
randr=randr.reshape(5,2)

In [34]:
randr.shape

(5, 2)

In [35]:
randr.dtype

dtype('int32')

In [ ]:
#indexing

In [36]:
arr=np.arange(0,11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[3]

3

In [39]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [40]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[0:5]=100

In [43]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
arr_copy=arr.copy()
arr_copy[:]=99
print(arr_copy)
print(arr)

[99 99 99 99 99 99 99 99 99 99 99]
[100 100 100 100 100   5   6   7   8   9  10]


In [47]:
arr_2d=np.array([[5,10,15],[20,25,30],[40,45,50]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [40, 45, 50]])

In [49]:
arr_2d[2][0]

40

In [50]:
arr_2d[2,0]

40

In [53]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [54]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
bol_array=arr>4
bol_array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [58]:
arr[bol_array]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [60]:
arr[arr<3]

array([1, 2])

In [63]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [64]:
 arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [65]:
arr_2d[3:,8:]

array([[38, 39],
       [48, 49]])

In [66]:
#numpy operations


In [75]:
arr=np.arange(0,11)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
arr*8

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [78]:
arr/0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
#universal array funtions

In [79]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [80]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [82]:
arr.max()

10

In [83]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [84]:
import time

In [85]:
np.random.seed(time.time())

TypeError: Cannot cast array from dtype('float64') to dtype('int64') according to the rule 'safe'